name: 'Inclusiveness Analyzer'
description: 'This GitHub action scans your repository for non-inclusive terms and provide alternative suggestions.'
inputs:
  fail-build:  # id of input
    description: 'Fails the build if a non-inclusive term is found'
    required: false
    default: 'false'
  exclude-terms:
    description: 'Comma separated list of non-inclusive terms to exclude from analysis'
    required: false
  exclude-from-scan:
    description: 'Comma separated list of file patterns to exclude from analysis'
    required: false
runs:
  using: 'node16'
  main: 'dist/index.js'

branding:
  icon: 'heart'
  color: 'green'
