name: 'Inclusiveness Analyzer'
description: 'This GitHub action scans your repository for non-inclusive terms and provide alternative suggestions.'
inputs:
  who-to-greet:  # id of input
    description: 'Who to greet'
    required: false
    default: 'World'
  outputType:
    description: 'Output results as "failure" or "warning".'
    required: false
    default: 'warning'
outputs:
  time: # id of output
    description: 'The time we greeted you'
runs:
  using: 'node16'
  main: 'dist/index.js'

branding:
  icon: 'heart'
  color: 'green'
