name: Test

on:
  [push]

jobs:
  code_stability_test:
    runs-on: ubuntu-latest
    name: Code stability test. Run analyzer against our own code.
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Install
        uses: bahmutov/npm-install@v1
      - name: Build
        run: yarn build
      - name: Inclusiveness Analyzer action step
        id: analyzer
        uses: ./